//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInfo
    {
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomarPhn { get; set; }
        public string CustomerArea { get; set; }
        public string CustomarAddress { get; set; }
        public string CustomerEmail { get; set; }
    }
}
