//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string ProductTittle { get; set; }
        public string ProductCode { get; set; }
        public decimal SalesPrice { get; set; }
        public int InitialProductStockQty { get; set; }
        public int RemainingQty { get; set; }
        public int QRId { get; set; }
        public string PPicture { get; set; }
    }
}
