//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QR
    {
        public int ID { get; set; }
        public int ItemCode { get; set; }
        public string ItemName { get; set; }
        public decimal PriceAmount { get; set; }
        public byte[] QrImage { get; set; }
        public string QrCategory { get; set; }
        public int QrQty { get; set; }
        public int UserID { get; set; }
    }
}
