//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesProduct
    {
        public int SalesProID { get; set; }
        public int SaleID { get; set; }
        public int ProductID { get; set; }
        public int OrderQty { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Amount { get; set; }
        public decimal Pvat { get; set; }
        public decimal PDiscount { get; set; }
        public bool Returnable { get; set; }
    }
}
